---
- name: add PPA
  apt_repository: repo="ppa:ondrej/php5"

- name: ensure PHP installed
  apt: pkg={{ item }} state=latest
  with-items:
    - php5-fpm
    - php5-dev
    - php5-cli
    - php5-json
    - php5-curl
    - php5-intl
    - php5-pgsql
    - php5-sqlite
    - php5-gd
    - php5-mcrypt
    - php5-xdebug
    - php5-memcached
    - php5-apc
  tags: php

- name: install composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: copy pool configuration
  tempate: src=www.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm

- name: start php-fpm
  service: name=php5-fpm state=started enabled=true


